name: eat_caias
description: Canteen App for CAIAS
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  google_nav_bar: ^5.0.6
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  password_strength: ^0.2.0
  form_validator: ^2.1.1
  profanity_filter: ^2.0.0
  supabase_flutter: ^2.5.3
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2
  flutter_styled_toast: ^2.2.1
  gettext: ^1.2.0
  get: ^4.6.6
  shimmer_animation: ^2.1.0+1
  upi_india: ^3.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/cart-empty.png

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.otf
        - asset: assets/fonts/Outfit-Bold.otf
          weight: 900
        - asset: assets/fonts/Outfit-Medium.otf
          weight: 600
        - asset: assets/fonts/Outfit-SemiBold.otf
          weight: 700